plugins {
    id 'com.android.library'
}

android {
    namespace 'com.zuxoplayer.app'
    compileSdk null

    defaultConfig {
        minSdk 21


    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }
}

dependencies {
	// TODO: dependencies
}
